services:
  - type: web
    name: twdWatcher
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
